### ISSUE TITLE
warning: possible EventEmitter memory leak detected. 11 finish listeners added. 

### ISSUE THREAD

**Issue by KeKs0r** [hapijs/good-console#56] opened 2015-11-21 16:03 UTC
I experience in my tests that somehow the logging stream is not cleaned up when my server shuts down.

I created a testcase that starts and stops the server 11 times and the 11th time, this error occurs:
```
(node) warning: possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Socket.addListener (events.js:239:17)
    at Socket.Readable.on (_stream_readable.js:655:33)
    at Socket.once (events.js:265:8)
    at DestroyableTransform.Readable.pipe (/Users/marc/Sites/hapigamb/node_modules/good-console/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:581:8)
    at internals.GoodConsole.init (/Users/marc/Sites/hapigamb/node_modules/good-console/lib/index.js:101:9)
    at /Users/marc/Sites/hapigamb/node_modules/good/lib/monitor.js:163:18
    at iterate (/Users/marc/Sites/hapigamb/node_modules/good/node_modules/items/lib/index.js:35:13)
    at Object.exports.serial (/Users/marc/Sites/hapigamb/node_modules/good/node_modules/items/lib/index.js:38:9)
    at internals.Monitor.start (/Users/marc/Sites/hapigamb/node_modules/good/lib/monitor.js:126:11)
    at Object.exports.register (/Users/marc/Sites/hapigamb/node_modules/good/lib/index.js:17:20)
    at Object.target [as register] (/Users/marc/Sites/hapigamb/node_modules/hapi/node_modules/joi/lib/object.js:79:30)
    at Items.serial.self.root._registring (/Users/marc/Sites/hapigamb/node_modules/hapi/lib/plugin.js:317:14)
    at iterate (/Users/marc/Sites/hapigamb/node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at Object.exports.serial (/Users/marc/Sites/hapigamb/node_modules/hapi/node_modules/items/lib/index.js:38:9)
    at internals.Plugin.register (/Users/marc/Sites/hapigamb/node_modules/hapi/lib/plugin.js:249:11)
    at /Users/marc/Sites/hapigamb/node_modules/glue/lib/index.js:109:20
    at iterate (/Users/marc/Sites/hapigamb/node_modules/glue/node_modules/items/lib/index.js:35:13)
    at Object.exports.serial (/Users/marc/Sites/hapigamb/node_modules/glue/node_modules/items/lib/index.js:38:9)
    at /Users/marc/Sites/hapigamb/node_modules/glue/lib/index.js:107:15
    at /Users/marc/Sites/hapigamb/node_modules/glue/lib/index.js:115:9
    at iterate (/Users/marc/Sites/hapigamb/node_modules/glue/node_modules/items/lib/index.js:35:13)
    at done (/Users/marc/Sites/hapigamb/node_modules/glue/node_modules/items/lib/index.js:27:25)
    at /Users/marc/Sites/hapigamb/node_modules/glue/lib/index.js:77:13
    at /Users/marc/Sites/hapigamb/node_modules/glue/lib/index.js:115:9
    at iterate (/Users/marc/Sites/hapigamb/node_modules/glue/node_modules/items/lib/index.js:35:13)
    at done (/Users/marc/Sites/hapigamb/node_modules/glue/node_modules/items/lib/index.js:27:25)
    at /Users/marc/Sites/hapigamb/node_modules/glue/lib/index.js:68:9
    at /Users/marc/Sites/hapigamb/node_modules/glue/lib/index.js:115:9
    at iterate (/Users/marc/Sites/hapigamb/node_modules/glue/node_modules/items/lib/index.js:35:13)
    at done (/Users/marc/Sites/hapigamb/node_modules/glue/node_modules/items/lib/index.js:27:25)
    at /Users/marc/Sites/hapigamb/node_modules/glue/lib/index.js:50:13
    at /Users/marc/Sites/hapigamb/node_modules/glue/lib/index.js:115:9
    at iterate (/Users/marc/Sites/hapigamb/node_modules/glue/node_modules/items/lib/index.js:35:13)
    at Object.exports.serial (/Users/marc/Sites/hapigamb/node_modules/glue/node_modules/items/lib/index.js:38:9)
    at Object.exports.compose (/Users/marc/Sites/hapigamb/node_modules/glue/lib/index.js:113:11)
    at compose (/Users/marc/Sites/hapigamb/lib/happier/server.js:85:10)
    at Object.start (/Users/marc/Sites/hapigamb/lib/happier/server.js:92:5)
    at /Users/marc/Sites/hapigamb/test/index.spec.js:86:22
    at Immediate._onImmediate (/Users/marc/Sites/hapigamb/node_modules/lab/lib/runner.js:455:17)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

**Comment by arb** [comment] 2015-11-21 17:12
When I run `npm test` in the good-console directory, I do not see this error. What version of node are you using? Also, that's a pretty hefty stack and it doesn't look like you are testing good-console directly.

**Comment by KeKs0r** [comment] 2015-11-23 07:06
I am on node 4.2.2 and using those dependencies:
```
    "good": "~6.4.0",
    "good-console": "^5.2.0",
```

No my tests are not testing good console, they just start my hapi app 11x times and then shut it down again.

**Comment by arb** [comment] 2015-11-23 13:59
Yeah are you using wreck and listening for wreck events? That is generally where that error comes from. Since wreck is a singleton, every test attaches another event listener to the singleton and is never cleaned up. 

https://github.com/hapijs/good/blob/master/test/index.js#L11-L12

**Comment by KeKs0r** [comment] 2015-11-24 06:51
I am not using Wreck directly, I am using h2o2, so I can't even directly require wreck to set MaxListeners on it.

**Comment by arb** [comment] 2015-11-24 14:13
Good attaches a listener to wreck so if you are creating your server over and over in your tests, that's what is going to cause it. Without seeing anything else, that is the best I can do. 

I'm going to close this issue as good-console doesn't even have a reference to wreck and the problem is not originating from this module. If you need additional help, open an issue at https://github.com/hapijs/discuss/issues.

**Closed by arb** 2015-11-24 14:13 UTC

**Comment by KeKs0r** [comment] 2015-11-24 14:32
I am not 100% sure if this issue is actually related to wreck. I was able to get rid of the warning by changing the the GoodConsole.init function:

```javascript
internals.GoodConsole.prototype.init = function (stream, emitter, callback) {
    var self = this;

    if (!stream._readableState.objectMode) {
        return callback(new Error('stream must be in object mode'));
    }


    var filter = this._filter;
    var transform = Through.obj(function goodConsoleTransform (data, enc, next) {

        var eventName = data.event;
        var tags = [];

        /*eslint-disable */
        if (Array.isArray(data.tags)) {
            tags = data.tags.concat([]);
        } else if (data.tags != null) {
            tags = [data.tags];
        }
        /*eslint-enable */

        tags.unshift(eventName);

        if (eventName === 'response') {
            this.push(self._formatResponse(data, tags));
            return next();
        }

        if (eventName ===  'wreck') {
            this.push(self._formatWreck(data, tags));
            return next();
        }

        var eventPrintData = {
            timestamp: data.timestamp || Date.now(),
            tags: tags,
            data: undefined
        };

        if (eventName === 'ops') {
            eventPrintData.data = Hoek.format('memory: %sMb, uptime (seconds): %s, load: %s',
                Math.round(data.proc.mem.rss / (1024 * 1024)),
                data.proc.uptime,
                data.os.load);

            this.push(self._printEvent(eventPrintData));
            return next();
        }

        if (eventName === 'error') {
            eventPrintData.data = 'message: ' + data.error.message + ' stack: ' + data.error.stack;

            this.push(self._printEvent(eventPrintData));
            return next();
        }

        if (eventName === 'request' || eventName === 'log') {
            eventPrintData.data = 'data: ' + (typeof data.data === 'object' ? SafeStringify(data.data) : data.data);

            this.push(self._printEvent(eventPrintData));
            return next();
        }

        // Event that is unknown to good-console, try a defualt.
        if (data.data) {
            eventPrintData.data = 'data: ' + (typeof data.data === 'object' ? SafeStringify(data.data) : data.data);
        }
        else {
            eventPrintData.data = 'data: (none)';
        }

        this.push(self._printEvent(eventPrintData));
        return next();
    })

    var first = stream.pipe(filter);
    var second = first.pipe(transform);
    var last = second.pipe(process.stdout);

    emitter.on('stop', function(){
        stream.emit('close');
        first.emit('close');
        second.emit('close');
        last.emit('close');
    })


    callback();
};
```

Not sure if this is a good approach, if so I would create a PR.

**Comment by arb** [comment] 2015-11-24 15:21
What did you change? That is a lot of code.

**Comment by KeKs0r** [comment] 2015-11-24 15:52
the MAIN change is adding these: 
```
    emitter.on('stop', function(){
        stream.emit('close');
        first.emit('close');
        second.emit('close');
        last.emit('close');
    })
```
rest is smaller refactoring, I could try to only emit a close event on the last stream, maybe its sufficient. Ill create a PR, in order to make comparison easier.

**Comment by arb** [comment] 2015-11-24 16:02
Again; when I run the tests on just good-console, I don't have this issue. 

Also, you shouldn't be emitting anything on `stream` because that object is being passed around to a bunch of other reporters and you have no idea what the downstream impact is of emitting a "close" event on a stream that is being consumed by multiple other streams. 

If you can create an example using ONLY good-console that shows this error, then we can look at trying to make it go away. At present, I am not convinced that the issue is in good-console.

**Comment by KeKs0r** [comment] 2015-11-24 16:09
I have now done the minimal necessary change to get rid of this error in #58. 

My Testcase for it was just starting my server 11 times. 
So any example app with good console should be able to reproduce this issue, unfortunately the good-console testcases, are not embedded within hapi, so its not that easy to show that behaviour.

**Comment by arb** [comment] 2015-11-24 16:12
There isn't an error though. The error is coming from somewhere else. If you open `good-console` and run `npm test`, this message is not printed. As I said earlier, it's probably the registration of good - https://github.com/hapijs/good/blob/master/lib/monitor.js#L186 that line happens 11 times and adds 11 listeners to the wreck instance.

**Comment by KeKs0r** [comment] 2015-11-24 16:43
I have created a sample app that reproduces the error: https://github.com/KeKs0r/hapi-good 
`node_modules/lab/bin/lab test.js `

You could replace the good console with my version in order to show that the error is gone afterwards

**Comment by arb** [comment] 2015-11-24 19:58
I pulled your code and fiddled with it. The problem is that when good is stopped (https://github.com/hapijs/good/blob/master/lib/monitor.js#L201) it does push `null` through the `_dataStream` readable stream. When I make that change to the local install of Good, the tests pass fine without the warning. The issue was on piping to `process.stdout` as that is ALSO a singleton (like Wreck). 

While this obviously isn't correct for Good to not tear down these streams properly, I'm hesitant to make this change in Good because it may have many downstream impacts on the existing reporter ecosystem. That being said, there is a version 7 branch of good, and I'll be sure to add this change there.
